<?php if(Mage::getStoreConfig('customproduct/custom_footer/enable')) : ?>
<?php
    $tabOptions = Mage::getStoreConfig('customproduct/custom_footer/custom_option');    
    $displayBlock = false;
    $tabArray = array();
    if ($tabOptions != null || $tabOptions != " ") {
        $displayBlock = true;
        $firstTab = true;
        $tabOptions = explode(",",$tabOptions);        
        $displayOrder = Mage::getStoreConfig('customproduct/custom_footer/order_options');
        if ($displayOrder != null && $displayOrder != "") {
            $displayOrder = explode(",",$displayOrder);
            foreach ($displayOrder as $order) {
                foreach ($tabOptions as $tab) {
                    $tabValue = explode("_",$tab);
                    if($tabValue[0] == $order) {
                        $tabArray[] = $tabValue[1];
                    }
                }
            }
        }
        else {            
            foreach ($tabOptions as $tab) {
                $tabValue = explode("_",$tab);                
                $tabArray[] = $tabValue[1];          
            }
        }
    }   
    $activeTab = "_customlistfooter";
    
?>
        

        <?php //echo $this->getLayout()->createBlock('customproduct/product'.$activeTab)->setCustomproduct($tabArray)->setBlockLimitId("1c")->setTemplate('catalog/product/customproduct/footerlist.phtml')->toHtml(); ?>
        <?php
        $attributeId = Mage::getResourceModel('eav/entity_attribute')->getIdByCode('catalog_product','product_footer_option');
            
        $attribute = Mage::getModel('catalog/resource_eav_attribute')->load($attributeId);
        $attributeOptions = $attribute ->getSource()->getAllOptions();
        $getAllPossibleArray = $tabArray;

            foreach ($getAllPossibleArray as $attrKey => $attrValue) {
                foreach ($attributeOptions as $attropKey => $attropValue) {
                        if(strtolower($attropValue['label']) == strtolower($attrValue)) {
                        $filterId = $attropValue['value'];
                        break;
                        }
                }

                $collection = Mage::getResourceModel('catalog/product_collection');
                Mage::getModel('catalog/layer')->prepareProductCollection($collection);
            
               $collection->addAttributeToFilter('product_footer_option', array('finset'=>$filterId))
                        ->addStoreFilter();
                
                
                $limit = Mage::getStoreConfig('customproduct/custom_footer/product_load_max');
                if($limit == "")
                {
                    $limit = 20;
                }

                $collection->setPage(1, $limit)->load();
                $collectionData[$attrValue] = $collection->getData();
            }
             // echo "<pre>"; print_r($collectionData); die;
            $_helper = $this->helper('catalog/output');    
            $display_productname_singleline = Mage::getStoreConfig('frontslash_settings/product_list/display_productname_singleline');
            $image_aspect_ratio = Mage::getStoreConfig('frontslash_settings/product_list/image_aspect_ratio');
            $product_style = Mage::getStoreConfig('frontslash_settings/product_list/product_style');

        ?>

        <div class=" <?php echo 'product-style'.$product_style; ?>">
    <?php foreach ($collectionData as $attrKey=> $attrVal): 
?>
            <h2><?php echo $attrKey; ?></h2>
            <?php
                foreach ($attrVal as $key => $prdVal) {
                    //echo "<pre>"; print_r($prdVal); die;
                    $_product = Mage::getModel("catalog/product")->load($prdVal['entity_id']);
                    // echo "<pre>"; print_r($_product->getData()); die;
                    ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">

                    <?php if($image_aspect_ratio == '1'){ ?>
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(true)->keepAspectRatio(true)->keepFrame(false)->resize(30,0) ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    <?php } else { ?>
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(true)->resize(30,30) ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    <?php } ?>
                    </a>
                    <div class="product-content-wrapper">
                        <div class="product-content">
                        
                        <h3 class="product-name<?php if($display_productname_singleline == '1'){ ?> single-line-name<?php } ?>"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->htmlEscape($_product->getName()); ?></a></h3>
                        <div class="vert">
                            <?php //echo number_format($_product->getPrice(),2); 
                                $product_block = new Mage_Catalog_Block_Product;
                                echo $product_block->getPriceHtml($_product);
                                unset($product_block);

                            ?>              
                        </div>
                        </div>
                    </div>
                    <?php

                }
        
            

    ?>
        </div>
                            
    <?php endforeach ?>
    </div>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
<?php endif; ?>